### ISSUE TITLE
Vulnerable version of urllib3 is installed

### ISSUE THREAD

**Issue by sashasimkin** [URLR/urlr-python#1]
Hi!

In my project I have dependabot reporting this vulnerability: https://github.com/advisories/GHSA-34jh-p97f-mpxf

I've tracked down to this package the old version of `urllib3` being installed.

The problem is `urlr` has an old constraint for the packages:

https://github.com/URLR/urlr-python/blob/main/setup.py#L28

Even though the requirements.txt was already updated: https://github.com/URLR/urlr-python/blob/main/requirements.txt

Please fix the requirements and make a new release.

**Comment by Huluti** [comment]
Hello.
I'll will do it today thanks for the report!

**Comment by Huluti** [comment]
It should be good now with v2.5.1.
Can you confirm?

**Comment by sashasimkin** [comment]
Hi!
Thank you so much for your rapid reaction!
It is good now! 🎉
